### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by mpaccione** [Clark-Whitehead/asklana#4]
Currently, the state slice is outside of the store and would best be located in a redux folder.
There are other issues with structuring. Take a look at below as a reference.
https://github.com/mpaccione/full-stack-todo-2022

**Comment by Clark-Whitehead** [comment]
I don't know what you mean by putting a slice in a store. I just import to the store so it's clearner. Where are you getting your info?

**Comment by mpaccione** [comment]
You put the slices with the store inside a redux folder. 
It's a scalability factor. Basically your approach right now is a non segregation one. 
As a parallel there is normally an assets folder where all the media goes. It typically wouldn't be stored in the folder it's used in unless it's a project that consists of only a handful of files or if it's a package dependency of shared components.

**Comment by Clark-Whitehead** [comment]
I'm implementing all the different ways of state handling. I'm currently on prop drilling. Will end with redux-toolkit. My structures will probably change then. This is currently the Codeacademy structure.

**Comment by mpaccione** [comment]
Cool yeah enjoy the process.

```
/public
/src
   /api
   /assets 
   /components
   /redux
      slice1.js
      store.js
   /views
      /viewA
         /actions
            index.js
         /components
            Component1.jsx
         index.js
   App.js
   index.js
```
